name: Telegram Bot Test

on:
  workflow_dispatch:

jobs:
  send-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y curl jq

      - name: Fetch quote
        run: |
          RESPONSE=$(curl -s https://api.quotable.io/random)
          QUOTE=$(echo "$RESPONSE" | jq -r '.content')
          AUTHOR=$(echo "$RESPONSE" | jq -r '.author')

          echo "QUOTE=$QUOTE" >> $GITHUB_ENV
          echo "AUTHOR=$AUTHOR" >> $GITHUB_ENV

      - name: Send to Telegram
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          TEXT="Random Quote: \"$QUOTE\" â€” $AUTHOR"

          curl -sS "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
            --data-urlencode "chat_id=-1002868007272" \
            --data-urlencode "message_thread_id=384" \
            --data-urlencode "text=$TEXT"
